_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
